const TYPES = {
  AGREGAR_AL_CARRITO: "AGREGAR_AL_CARRITO",
  ELIMINAR_TODO_DEL_CARRITO: "ELIMINAR_TODO_DEL_CARRITO",
  ELIMINAR_PRODUCTO_DEL_CARRITO: "ELIMINAR_PRODUCTO_DEL_CARRITO"
}

export default TYPES;